spring:
  application:
    name: service-booking

  datasource:
    url: jdbc:postgresql://localhost:5432/service_booking_db
    username: postgres
    password: Cqs030104
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

server:
  port: 8080
